---
{{ $values := .Values -}}
---
{{ range $ns := .Values.projects -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view
  namespace: "{{ $ns.name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ $values.adGroup }}"
---
{{ end }}